name: Node.js CI & Test

on:
  push:
    branches: [ main ] # Or your default branch, e.g., master
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Choose a Node.js version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # 'ci' is generally recommended for CI for cleaner installs

    - name: Build CSS (optional, but good to check if build breaks)
      run: npm run build-css

    - name: Run tests
      run: npm test

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4.6.2
      with:
        name: coverage-report # Name of the artifact
        path: coverage/       # Path to the directory to upload
        if-no-files-found: error # Optional: fail if coverage/ directory is not found